config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :memberships
  end
  root :to => 'groups#index'
end

app/models/group.rb
class Group < ActiveRecord::Base
  set_table_name "abstract_group_groups"
  
  include Groupable
  
  has_many :registered_memberships, {
    :class_name => "Membership",
    :table_name => Membership.table_name,
    :dependent => :destroy
  }
  
  validates_uniqueness_of :name
  validates_length_of :name, :within => (4..255)
  
  def members
    return [] if registered_memberships.count == 0
    registered_memberships.find(:all).collect do |membership|
      membership.member
    end
  end
  
  def self.abstract_class?
    false
  end
end

app/models/groupable.rb
module Groupable

  @@types ||= []
  
  def self.included(base)
    @@types << base
    
    base.instance_eval do
      include Associations
    end
  end
  def self.types
    (@@types - [Group]).reverse
  end
  def self.abstract_class?
    false
  end
  # Contains association declarations for tying together arbitrary objects
  # with group objects.
  module Associations
    def self.included(base)
      base.instance_eval do
        has_many :memberships, {:as => :member, :dependent => :destroy}
        has_many :groups, {:through => :memberships}
      end
    end
  end
end

app/models/member.rb
class Member
  def self.create!(membership_hash)    
    group_id = membership_hash.delete :group_id
    memberships = []
    membership_hash.each do |member_class, member_ids|
      #member_class = member_class.to_s.classify.constantize
      #raise "#{member_class} - #{Groupable.types.inspect}"
      member_class = Groupable.types.detect{|t| t.to_s.downcase == member_class.singularize}
      if Groupable.types.include?(member_class)
        member_ids.each do |member_id|
          next if member_id.blank? || member_class.blank?
          memberships << Membership.create!({
            :group_id => group_id,
            :member_id => member_id,
            :member_type => member_class
          })
        end
      end
    end
    memberships
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  set_table_name "abstract_group_memberships"
  
  belongs_to :group
  belongs_to :member, :polymorphic => true
end

app/controllers/abstract_group/application_controller.rb
class AbstractGroup::ApplicationController < ApplicationController
  protect_from_forgery

  prepend_before_filter :use_engine_assets if Rails.env != 'production'
  prepend_before_filter :setup_asset_path if defined?(AbstractGroup::Engine)
  
  private
    def use_engine_assets
      require 'abstract_group/action_view'
    end
    def setup_asset_path
      config.asset_path = '/abstract_group%s'
    end
  protected
  public
end

app/controllers/abstract_group_controller.rb
class AbstractGroupController < ApplicationController

  helper_method :engine_path
  
  private
    def registered_engines
      Rails::Engine.subclasses.map do |sc|
        sc.to_s.underscore.gsub("/engine", "")
      end << 'main_app'
    end
    def engine_path(obj_or_class, options={})
      class_name = obj_or_class.kind_of?(Class) ? obj_or_class.to_s : obj_or_class.class.to_s
      
      @cached_engine_classes ||= {}
      
      return_path = ''
      if @cached_engine_classes[class_name]
        return_path = send(@cached_engine_classes[class_name]).polymorphic_path(obj_or_class, options)
      end
      
      count = 0
      while return_path.blank? do
        begin
          if registered_engines[count].blank?
            return_path = "/"
          else
            return_path = send(registered_engines[count]).polymorphic_path(obj_or_class, options)
            
            @cached_engine_classes[class_name] = registered_engines[count]
          end
        rescue NoMethodError => e
          logger.debug(e.message)
          count += 1
          retry
        end
      end
      return_path
    end
  protected
  public
end

app/controllers/application_controller.rb
# stub to allow standalone mode
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < AbstractGroup::ApplicationController
  
  private
    def load_groups
      @groups = Group.find(:all, :order => 'name')
    end
    def load_new_group
      @group = Group.new(params[:group])
    end
  protected
  public  
    def index
      load_groups
    end
    def new
      load_groups
      load_new_group
    end
    def show
      @group = Group.find(params[:id])
    end
    def edit
      @group = Group.find(params[:id])
      load_groups
    end
    def create
      load_new_group
      if @group.save
        flash[:notice] = "Group successfully created!"
        redirect_to group_path(@group)
      else
        load_groups
        render :new
      end
    end
    def update
      @group = Group.find(params[:id])
      if @group.update_attributes(params[:group])
        flash[:notice] = "Group successfully updated!"
        redirect_to group_path(@group)
      else
        load_groups
        render :edit
      end
    end
    def destroy
      group = Group.destroy(params[:id])
      flash[:notice] = "Group deleted."
      redirect_to groups_path
    end
end

app/controllers/memberships_controller.rb
class MembershipsController < AbstractGroup::ApplicationController
  
  before_filter :load_group
  
  rescue_from ActiveRecord::RecordInvalid, :with => :invalid_record

  include ActionView::Helpers::TextHelper # for pluralize in #create
  
  private
    def invalid_record(e)
      if action_name == 'create'
        flash.now[:notice] = "A processing error occurred while attempting "+
                             "to create the selected memberships."
                             
        
        @groups = Group.all
        @members = Groupable.types.collect do |type|
          type.send(:find, :all)
        end.flatten
        render :new
      end
    end
    def load_group
      if params[:group_id]
        @group = Group.find(params[:group_id])
      else
        redirect_to(groups_path, {
          :notice => "Which group does the new membership apply to?"
        })
      end
    end
  protected
  public
    def new
      @membership = Membership.new
      @groups = Group.all
      @members = Groupable.types.collect do |type|
          type.send(:find, :all)
      end.flatten
    end
    def create
      memberships = Member.create!(params[:membership])
      redirect_to(groups_path, {
        :notice => "Created #{pluralize(memberships.count, 'Membership')}!"
      })
    end
end

app/helpers/abstract_group/application_helper.rb
module AbstractGroup::ApplicationHelper
  def link_wrapper(path, wrapper_options={}, link_options={})
    tag       = wrapper_options.delete(:tag) || :p
    link_text = link_options.delete(:link_text) || path
    highlight = wrapper_options.delete(:highlight)
  
    unless path.blank?
      if current_page?(path) && (highlight.nil? || highlight)
        wrapper_options = {:class => (wrapper_options[:class] || '') + " nav_highlight"}
      end
    end

    unless wrapper_options.delete(:no_wrapper)
      return content_tag(tag, wrapper_options) do
        link_to(link_text, path, link_options)
      end
    else
      return link_to(link_text, path, link_options)
    end
  end
  def abstract_group_checkboxes(form)
    render :partial => 'groups/group_checkboxes', :object => form
  end

  def link_to_groups(wrapper_options={})
    link_wrapper(groups_path, wrapper_options, {
      :link_text => "Full list of Groups (#{Group.count})"
    })
  end

  def link_to_new_group(wrapper_options={})
    link_wrapper(new_group_path, wrapper_options, {
      :link_text => "Create New Group"
    })
  end

  def link_to_new_group_membership(group, wrapper_options={})
    link_wrapper(new_group_membership_path(group), wrapper_options, {
      :link_text => "Create New Membership"
    })
  end
  
  def render_abstract_group_main_menu
    render :partial => 'abstract-group-shared/main_menu'
  end
  
  def render_abstract_group_navigation(group=nil)
    render :partial => 'abstract-group-shared/navigation', :locals => {
      :group => group
    }
  end
  
  def abstract_group_stylesheet_includes
    [
      "abstract_group",
      "formtastic",
      "formtastic_changes"
    ]
  end
  def abstract_group_javascript_includes
    [
      "jquery-1.4.1.min.js",
      "rails"
    ]
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/abstract-group-shared/_flash.html.erb
<% if flash[:notice] || flash[:warning] %>
  <div id="flash_message">
    <div class="<%= flash[:notice] ? 'notice' : 'error' %>">
      <p><%= flash[:notice] || flash[:warning] %></p>
    </div>
  </div>
<% end %>

app/views/abstract-group-shared/_main_menu.html.erb
<ul>
  <li><%= link_to "Groups", groups_path %></li>
</ul>

app/views/abstract-group-shared/_navigation.html.erb
  <h4>Explore Groups</h4>
  <%= link_to_groups %>
  <h4>Manage Groups</h4>
  <%= link_to_new_group %>
  <% if defined?(group) && !group.nil? && !group.new_record? %>
  <%= link_to_new_group_membership(@group) %>
  <% end %>

app/views/groups/_form.html.erb
<%= form.inputs do %>
  <%= form.input :group_ids, :label => "Group", :as => :select, :collection => @groups %>
  <%= form.input :name %>
<% end %>
<%= form.submit %>

app/views/groups/_group_checkboxes.html.erb
<%= group_checkboxes.inputs do %>
  <%= group_checkboxes.input :groups, :as => :check_boxes %>
<% end %>

app/views/groups/edit.html.erb
<%= semantic_form_for(@group, :url => group_path(@group)) do |form| %>
  <%= render :partial => 'form', :object => form %>
<% end %>

app/views/groups/index.html.erb
<table class="nice_table tablesorter">
  <thead>
    <tr>
      <th>Group</th>
      <th>Memberships</th>
      <th colspan="3">Manage</th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
    <tr>
      <td><%= link_to group.name, group_path(group) %></td>
      <td><%= group.members.group_by(&:class).map{|t,m| 
        link_to(pluralize(m.size, t.to_s), polymorphic_path(t))}.join("; ").html_safe %></td>
      <td><%= link_to "add members", new_group_membership_path(group), :class => 'fake_button' %></td>
      <td><%= link_to("edit", edit_group_path(group), :class => 'fake_button') %></td>
      <td><%= link_to("delete", group_path(group), {
        :class => 'fake_button',
        :method => 'delete',
        :confirm => 'Are you sure you want to delete this group?'
      })%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<%= semantic_form_for(@group, :url => groups_path) do |form| %>
  <%= render :partial => 'form', :object => form %>
<% end %>

app/views/groups/show.html.erb
<h3><%= @group.name %></h3>
<p>Memberships: <%= @group.registered_memberships.count %></p>
<% @group.members.group_by(&:class).map do |type, members| %>
  <h4><%= link_to(pluralize(members.size, type.to_s), polymorphic_path(type)) %></h4>
  <ol>
  <% members.each do |member| %>
    <% name_attr = member.attribute_names.detect{|m_attr| m_attr =~ /name/} %>
    <% if name_attr %>
    <li><%= link_to(member.send(name_attr), polymorphic_path(member)) %></li>
    <% end %>
  <% end %>
  </ol>
<% end %>

app/views/layouts/abstract-group.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>Abstract Group</title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag "blueprint/screen", :media => "screen, projection" %>
    <%= stylesheet_link_tag "blueprint/print", :media => "print" %>
    <%= stylesheet_link_tag "blueprint/src/grid", :media => "screen, projection" %>
    
    <!--[if lt IE 8]>
      <%= stylesheet_link_tag "blueprint/ie", :media => "screen, projection" %>
    <![endif]-->

    <%= stylesheet_link_tag "abstract_group", "formtastic", "formtastic_changes" %>
    
    <%= javascript_include_tag 'jquery-1.4.1.min.js', 'rails' %>
    <%= yield :javascript %>
  </head>
  <body>
    <div class="container">
      <div class="top-banner span-24 last">
        <div class="header span-14">
          <h1>Abstract Group</h1>
        </div>
      </div>

      <div class="base_content span-20">
        <%= render :partial => 'abstract-group-shared/flash', :object => flash %>
        <div class="inner_content">
          <%= yield %>
        </div>
      </div>

      <div class="span-4 last">
        <div class="sidebar">
          <%= render :partial => 'abstract-group-shared/navigation' %>
        </div>

      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>Abstract Group</title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag "blueprint/screen", :media => "screen, projection" %>
    <%= stylesheet_link_tag "blueprint/print", :media => "print" %>
    
    <!--[if lt IE 8]>
      <%= stylesheet_link_tag "blueprint/ie", :media => "screen, projection" %>
    <![endif]-->

    <%= stylesheet_link_tag abstract_group_stylesheet_includes %>    
    <%= javascript_include_tag abstract_group_javascript_includes %>
    
    <%= yield :javascript %>
  </head>
  <body>
    <div class="container">
      <div class="top-banner span-24 last">
        <div class="header span-14">
          <h1>Abstract Group</h1>
        </div>
      </div>

      <div class="base_content span-20">
        <%= render :partial => 'abstract-group-shared/flash', :object => flash %>
        <div class="inner_content">
          <%= yield %>
        </div>
      </div>

      <div class="span-4 last">
        <div id="main_menu">
          <%= render_abstract_group_main_menu %>
        </div>
        <div class="sidebar">
          <%= render :partial => 'abstract-group-shared/navigation', :locals => {
            :group => @group
          } %>
        </div>

      </div>
    </div>
  </body>
</html>

app/views/memberships/new.html.erb
<h2>Add Members to the <%= @group.name %> Group</h2>
<%= semantic_form_for(@membership, :url => group_memberships_path) do |form| %>
  <%= form.inputs do %>
    <%= form.input :group_id, :as => :hidden, :value => params[:group_id] %>
    <% @members.group_by(&:class).each do |type, members| %>
      <%= form.input type.to_s.downcase.pluralize, {
        :as => :check_boxes,
        :collection => members
      } %>
    <% end %>
  <% end %>
  <%= form.submit %>
<% end %>